# Enable git tasks
coreutils_enable_coreutils: true

# Enable nerdfonts tasks
coreutils_enable_nerdfonts: true
# Force installation regardles of it is already installed
coreutils_force_nerdfonts: false

# Enable git_delta tasks
coreutils_enable_git_delta: true
# Force installation regardles of it is already installed
coreutils_force_git_delta: false

# Enable rye tasks
coreutils_enable_rye: true

# Enable aws_cli tasks
coreutils_enable_aws_cli: true
# Force installation regardles of it is already installed
coreutils_force_aws_cli: false

# Enable tealdeer tasks
coreutils_enable_tealdeer: true
# Force installation regardles of it is already installed
coreutils_force_tealdeer: false

# Enable zoxide tasks
coreutils_enable_zoxide: true
# Force installation regardles of it is already installed
coreutils_force_zoxide: false

# Enable fzf tasks
coreutils_enable_fzf: true
# Force installation regardles of it is already installed
coreutils_force_fzf: false

# Enable fd tasks
coreutils_enable_fd: true
# Force installation regardles of it is already installed
coreutils_force_fd: false

# Enable sd tasks
coreutils_enable_sd: true
# Force installation regardles of it is already installed
coreutils_force_sd: false

# Enable ripgrep tasks
coreutils_enable_ripgrep: true
# Force installation regardles of it is already installed
coreutils_force_ripgrep: false

# Enable sd tasks
coreutils_enable_yq: true
# Force installation regardles of it is already installed
coreutils_force_yq: false

# Enable glow tasks
coreutils_enable_glow: true
# Force installation regardles of it is already installed
coreutils_force_glow: false

# Enable lf tasks
coreutils_enable_lf: true
# Force installation regardles of it is already installed
coreutils_force_lf: false

# Enable mmv tasks
coreutils_enable_mmv: true
# Force installation regardles of it is already installed
coreutils_force_mmv: false

# Enable mcfly tasks
coreutils_enable_mcfly: true
# Force installation regardles of it is already installed
coreutils_force_mcfly: false

# Enable lazygit tasks
coreutils_enable_lazygit: true
# Force installation regardles of it is already installed
coreutils_force_lazygit: false

# Enable git_cliff tasks
coreutils_enable_git_cliff: true
# Force installation regardles of it is already installed
coreutils_force_git_cliff: false
