
galaxy_info:
  author: Daniel von Essen
  description: Clones tokyonigh theme from github
  issue_tracker_url: https://gitlab.com/bitfooxyz/dots/-/issues
  license: MIT
  min_ansible_version: "2.1"
  galaxy_tags:
    - theme
    - tokyonigh

dependencies:
  - role: bitfoo.home.xdg_dirs
  - role: bitfoo.home.git
