collections:
  - name: https://github.com/geerlingguy/ansible-collection-mac
    type: git
roles:
  - src: git+https://github.com/elliotweiser/ansible-osx-command-line-tools.git
    name: elliotweiser.osx-command-line-tools
