galaxy_info:
  author: Daniel von Essen
  description: Install Applications on client
  issue_tracker_url: https://gitlab.com/bitfooxyz/dots/-/issues
  license: MIT
  min_ansible_version: "2.1"
  galaxy_tags:
    - application
    - homebrew
    - flatpak

dependencies:
  - name: bitfoo.home.flatpak
    when: 
      - ansible_system == "Linux"
      - applications_flatpak_enabled | bool
  - name: geerlingguy.mac.homebrew
    when: ansible_system == "Darwin"
