---
# XDG compliant dirs
xdg_dirs_cache: "{{ ansible_user_dir }}/.cache"
xdg_dirs_config: "{{ ansible_user_dir }}/.config"
xdg_dirs_local: "{{ ansible_user_dir }}/.local"
xdg_dirs_local_bin: "{{ ansible_user_dir }}/.local/bin"
xdg_dirs_local_share: "{{ ansible_user_dir }}/.local/share"
xdg_dirs_local_share_man: "{{ ansible_user_dir }}/.local/share/man"
xdg_dirs_local_state: "{{ ansible_user_dir }}/.local/state"
