galaxy_info:
  author: Daniel von Essen
  description: Install kube-linter from latest Github releases
  issue_tracker_url: https://gitlab.com/bitfooxyz/dots/-/issues
  license: MIT
  min_ansible_version: "2.1"
  galaxy_tags:
    - kubelinter
    - kubernetes

dependencies: []
