galaxy_info:
  author: Daniel von Essen
  description: Neovim installation and configuration role.
  issue_tracker_url: https://gitlab.com/bitfooxyz/dots/-/issues
  license: MIT
  min_ansible_version: "2.1"
  platforms:
    - name: Fedora
      versions:
        - all
    - name: MacOSX
      versions:
        - all

  galaxy_tags:
    - neovim
    - nvim
    - vim

