typeset -U path cdpath fpath manpath

# Some Special options
zstyle ':completion:*' completer _expand _complete _ignored _approximate
zstyle ':completion:*' special-dirs true
zstyle ':completions:*' cache-path $XDG_CACHE_HOME/.zcompcache-$ZSH_VERSION
# Make zsh now about ssh accessed hosts
zstyle -e ':completion:*:(ssh|scp|sftp|rsh|rsync):hosts' hosts 'reply=(${=${${(f)"$(cat {/etc/ssh_,~/.ssh/known_}hosts(|2)(N) /dev/null)"}%%[# ]*}//,/ })'

# Load colors into shell for colored-man-pages.plugin.zsh
autoload -U colors && colors

#source /nix/store/gd1i75n204liyhj9a9zmz6pxwy833frn-awscli2-2.15.34/share/zsh/site-functions/_aws
#source "/nix/store/2aqrcwm0z7bwrzgm9gpdj847vslxpaga-wezterm-20240203-110809-5046fc22/etc/profile.d/wezterm.sh"
#source /nix/store/ln7l614j50wjg8pddmzggrpk40iw1hlp-nix-index-0.1.7/etc/profile.d/command-not-found.sh

[ -f $XDG_CONFIG_HOME/zsh/exports.zsh ] && source $XDG_CONFIG_HOME/zsh/exports.zsh
[ -f $XDG_CONFIG_HOME/zsh/options.zsh ] && source $XDG_CONFIG_HOME/zsh/options.zsh
[ -f $XDG_CONFIG_HOME/zsh/bindings.zsh ] && source $XDG_CONFIG_HOME/zsh/bindings.zsh
[ -f $XDG_CONFIG_HOME/zsh/aliases.zsh ] && source $XDG_CONFIG_HOME/zsh/aliases.zsh
[ -f $XDG_CONFIG_HOME/zsh/plugins.zsh ] && source $XDG_CONFIG_HOME/zsh/plugins.zsh
[ -f $XDG_CONFIG_HOME/zsh/completions.zsh ] && source $XDG_CONFIG_HOME/zsh/completions.zsh
