- name: SHELL | Import xdg_dirs role
  ansible.builtin.import_role:
    name: xdg_dirs

- name: SHELL | Include os dependent vars
  ansible.builtin.include_vars:
    file: "{{ ansible_distribution | lower }}.yml"
  tags:
    - always

- name: SHELL | Install packages on Linux
  ansible.builtin.package:
    name: "{{ shell_packages }}"
    state: present
  become: true
  when: ansible_system == "Linux"
  tags:
    - always

- name: SHELL | Install packages on MacOS
  ansible.builtin.package:
    name: "{{ shell_packages }}"
    state: present
  become: true
  when: ansible_system == "Darwin"
  tags:
    - always

- name: SHELL | Copy shell profile to ~/.profile
  ansible.builtin.file:
    src: "{{ role_path }}/files/profile"
    dest: "{{ ansible_user_dir }}/.profile"
    state: link
    force: true
    mode: "0440"
  tags:
    - bash
    - zsh

- name: SHELL | Include bash tasks
  ansible.builtin.import_tasks:
    file: bash.yml
  tags:
    - bash

- name: SHELL | Include zsh tasks
  ansible.builtin.import_tasks:
    file: zsh.yml
  tags:
    - zsh

- name: SHELL | Import zsh plugins tasks
  ansible.builtin.import_tasks:
    file: zsh_plugins.yml
  tags:
    - zsh
    - zsh_plugins

- name: SHELL | Ensure zsh is default shell
  ansible.builtin.user:
    name: "{{ ansible_user_id }}"
    shell: /bin/zsh
  become: true
  tags:
    - zsh
