- name: SHELL | Import xdg_dirs role
  ansible.builtin.import_role:
    name: xdg_dirs

- name: SHELL | Import geerlingguy.mac.homebrew role
  ansible.builtin.import_role:
    name: geerlingguy.mac.homebrew
  when: ansible_system == "Darwin"

- name: SHELL | Include os dependent vars
  ansible.builtin.include_vars:
    file: "{{ ansible_distribution | lower }}.yml"

- name: SHELL | Install packages on Linux
  ansible.builtin.package:
    name: "{{ shell_packages }}"
    state: present
  become: true
  when: ansible_system == "Linux"

- name: SHELL | Install packages on MacOS
  community.general.homebrew:
    name: "{{ shell_packages }}"
    state: present
  when: ansible_system == "Darwin"

- name: SHELL | Copy shell profile to ~/.profile
  ansible.builtin.file:
    src: "{{ role_path }}/files/profile"
    dest: "{{ ansible_user_dir }}/.profile"
    state: link
    force: true
    mode: "0640"
  tags:
    - bash
    - zsh

- name: SHELL | Import bash tasks
  ansible.builtin.import_tasks:
    file: bash.yml
  tags:
    - bash

- name: SHELL | Import zsh tasks
  ansible.builtin.import_tasks:
    file: zsh.yml
  tags:
    - zsh

- name: SHELL | Import zsh plugins tasks
  ansible.builtin.import_tasks:
    file: zsh_plugins.yml
  tags:
    - zsh
    - zsh_plugins

- name: SHELL | Import work tasks
  ansible.builtin.import_tasks:
    file: work.yml
  when: shell_enable_work | bool
  tags:
    - zsh_work

- name: SHELL | Ensure zsh is default shell
  ansible.builtin.user:
    name: "{{ ansible_user_id }}"
    shell: /bin/zsh
  become: true
  tags:
    - zsh
