---
- name: ZSH | Install zsh on Linux
  ansible.builtin.package:
    name: "{{ shell_zsh_packages }}"
    state: present
  become: true
  when: ansible_system == "Linux"

- name: ZSH | Install zsh on MacOS
  community.general.homebrew:
    name: "{{ shell_zsh_packages }}"
    state: present
  when: ansible_system == "Darwin"

- name: ZSH | Create configuration directories in $XDG_CONFIG_HOME
  ansible.builtin.file:
    dest: "{{ xdg_dirs_config }}/{{ item }}"
    state: directory
    mode: "0750"
  loop:
    - zsh
    - zsh/completions
    - zsh/plugins

- name: ZSH | Link zshenv to ~/.zshenv
  ansible.builtin.file:
    src: "{{ role_path }}/files/zsh/zshenv"
    dest: "{{ ansible_user_dir }}/.zshenv"
    state: link
    force: true
    mode: "0640"

- name: ZSH | Link zshrc to ~/.config/zsh/.zshrc
  ansible.builtin.file:
    src: "{{ role_path }}/files/zsh/zshrc"
    dest: "{{ xdg_dirs_config }}/zsh/.zshrc"
    state: link
    force: true
    mode: "0640"

- name: ZSH | Link configuration to $XDG_CONFIG_HOME/zsh
  ansible.builtin.file:
    src: "{{ role_path }}/files/zsh/{{ item }}"
    dest: "{{ xdg_dirs_config }}/zsh/{{ item }}"
    state: link
    force: true
    mode: "0640"
  loop:
    - aliases.zsh
    - bindings.zsh
    - exports.zsh
    - options.zsh
    - plugins.zsh
