galaxy_info:
  author: Daniel von Essen
  description: Install and configure the awsome Wezterm terminal emulator

  # If the issue tracker for your role is not on github, uncomment the
  # next line and provide a value
  issue_tracker_url: https://gitlab.com/bitfooxyz/dots/-/issues

  # Choose a valid license ID from https://spdx.org - some suggested licenses:
  # - BSD-3-Clause (default)
  # - MIT
  # - GPL-2.0-or-later
  # - GPL-3.0-only
  # - Apache-2.0
  # - CC-BY-4.0
  license: MIT

  min_ansible_version: "2.9"

  # If this a Container Enabled role, provide the minimum Ansible Container version.
  # min_ansible_container_version:

  galaxy_tags:
    - wezterm
    - terminal

  # List your role dependencies here, one per line. Be sure to remove the '[]' above,
  # if you add dependencies to this list.
dependencies:
  - role: bitfoo.home.xdg_dirs
  - role: bitfoo.home.flatpak
    when:
      - ansible_system == "Linux"
      - ansible_distribution != "RedHat"
  - role: geerlingguy.mac.homebrew
    when: ansible_system == "Darwin"
  - role: bitfoo.home.tokyonight
