galaxy_info:
  author: Daniel von Essen
  description: Install ArgoCD from Github Releases
  issue_tracker_url: https://gitlab.com/bitfooxyz/dots/-/issues
  license: MIT
  min_ansible_version: "2.1"
  galaxy_tags:
    - argocd
    - argocd-cli
    - kubernetes

dependencies: []
