---
- name: COREUTILS | Import xdg_dirs role
  ansible.builtin.import_role:
    name: xdg_dirs

- name: COREUTILS | Import geerlingguy.homebrew rol
  ansible.builtin.import_role:
    name: geerlingguy.mac.homebrew
  when: ansible_system == "Darwin"

- name: COREUTILS | Import coreutils tasks
  ansible.builtin.import_tasks:
    file: coreutils/main.yml
  when: coreutils_enable_coreutils
  tags:
    - coreutils
