---
- name: COREUTILS | Import xdg_dirs role
  ansible.builtin.import_role:
    name: xdg_dirs

- name: COREUTILS | Import geerlingguy.homebrew rol
  ansible.builtin.import_role:
    name: geerlingguy.mac.homebrew
  when: ansible_system == "Darwin"

- name: COREUTILS | Import coreutils tasks
  ansible.builtin.import_tasks:
    file: coreutils/main.yml
  when: coreutils_enable_coreutils
  tags:
    - coreutils

- name: COREUTILS | Import nerdfonts tasks
  ansible.builtin.import_tasks:
    file: nerdfonts/main.yml
  when: coreutils_enable_nerdfonts
  tags:
    - nerdfonts

- name: COREUTILS | Import git-delta tasks
  ansible.builtin.import_tasks:
    file: git_delta/main.yml
  when: coreutils_enable_git_delta
  tags:
    - git_delta

- name: COREUTILS | Import rye tasks
  ansible.builtin.import_tasks:
    file: rye/main.yml
  when: coreutils_enable_rye
  tags:
    - rye

- name: COREUTILS | Import tealdeer tasks
  ansible.builtin.import_tasks:
    file: tealdeer/main.yml
  when: coreutils_enable_tealdeer
  tags:
    - tealdeer

- name: COREUTILS | Import zoxide tasks
  ansible.builtin.import_tasks:
    file: zoxide/main.yml
  when: coreutils_enable_zoxide
  tags:
    - zoxide

- name: COREUTILS | Import fzf tasks
  ansible.builtin.import_tasks:
    file: fzf/main.yml
  when: coreutils_enable_fzf
  tags:
    - fzf

- name: COREUTILS | Import sd tasks
  ansible.builtin.import_tasks:
    file: sd/main.yml
  when: coreutils_enable_sd
  tags:
    - sd

- name: COREUTILS | Import ripgrep tasks
  ansible.builtin.import_tasks:
    file: ripgrep/main.yml
  when: coreutils_enable_ripgrep
  tags:
    - ripgrep

- name: COREUTILS | Import yq tasks
  ansible.builtin.import_tasks:
    file: yq/main.yml
  when: coreutils_enable_yq
  tags:
    - yq

- name: COREUTILS | Import glow tasks
  ansible.builtin.import_tasks:
    file: glow/main.yml
  when: coreutils_enable_glow
  tags:
    - glow

- name: COREUTILS | Import lf tasks
  ansible.builtin.import_tasks:
    file: lf/main.yml
  when: coreutils_enable_lf
  tags:
    - lf

- name: COREUTILS | Import mmv tasks
  ansible.builtin.import_tasks:
    file: mmv/main.yml
  when: coreutils_enable_mmv
  tags:
    - mmv

- name: COREUTILS | Import mcfly tasks
  ansible.builtin.import_tasks:
    file: mcfly/main.yml
  when: coreutils_enable_mcfly
  tags:
    - mcfly

- name: COREUTILS | Import git_cliff tasks
  ansible.builtin.import_tasks:
    file: git_cliff/main.yml
  when: coreutils_enable_git_cliff
  tags:
    - git_cliff

- name: COREUTILS | Import lazygit tasks
  ansible.builtin.import_tasks:
    file: lazygit/main.yml
  when: coreutils_enable_lazygit
  tags:
    - lazygit
