---
- name: COREUTILS | Import xdg_dirs role
  ansible.builtin.import_role:
    name: xdg_dirs

- name: COREUTILS | Import geerlingguy.homebrew rol
  ansible.builtin.import_role:
    name: geerlingguy.mac.homebrew
  when: ansible_system == "Darwin"

# GIT tasks and vars
- name: COREUTILS | Import git tasks
  ansible.builtin.import_tasks:
    file: git/main.yml
  when: coreutils_enable_git
  tags:
    - git

- name: COREUTILS | Import nerdfonts tasks
  ansible.builtin.import_tasks:
    file: nerdfonts/main.yml
  when: coreutils_enable_nerdfonts
  tags:
    - nerdfonts

# BAT tasks and vars
- name: COREUTILS | Import bat tasks
  ansible.builtin.import_tasks:
    file: bat/main.yml
  when: coreutils_enable_bat
  tags:
    - bat
    - bat_extras

- name: COREUTILS | Import rye tasks
  ansible.builtin.import_tasks:
    file: rye/main.yml
  when: coreutils_enable_rye
  tags:
    - rye

- name: COREUTILS | Import aws_cli tasks
  ansible.builtin.import_tasks:
    file: aws_cli/main.yml
  when: coreutils_enable_aws_cli
  tags:
    - aws_cli

- name: COREUTILS | Import tealdeer tasks
  ansible.builtin.import_tasks:
    file: tealdeer/main.yml
  when: coreutils_enable_tealdeer
  tags:
    - tealdeer

- name: COREUTILS | Import zoxide tasks
  ansible.builtin.import_tasks:
    file: zoxide/main.yml
  when: coreutils_enable_zoxide
  tags:
    - zoxide

- name: COREUTILS | Import fzf tasks
  ansible.builtin.import_tasks:
    file: fzf/main.yml
  when: coreutils_enable_fzf
  tags:
    - fzf

- name: COREUTILS | Import fd tasks
  ansible.builtin.import_tasks:
    file: fd/main.yml
  when: coreutils_enable_fd
  tags:
    - fd

- name: COREUTILS | Import ripgrep tasks
  ansible.builtin.import_tasks:
    file: ripgrep/main.yml
  when: coreutils_enable_ripgrep
  tags:
    - ripgrep

- name: COREUTILS | Import glow tasks
  ansible.builtin.import_tasks:
    file: glow/main.yml
  when: coreutils_enable_glow
  tags:
    - glow

- name: COREUTILS | Import lf tasks
  ansible.builtin.import_tasks:
    file: lf/main.yml
  when: coreutils_enable_lf
  tags:
    - lf

- name: COREUTILS | Import eza tasks
  ansible.builtin.import_tasks:
    file: eza/main.yml
  when: coreutils_enable_eza
  tags:
    - eza

- name: COREUTILS | Import mmv tasks
  ansible.builtin.import_tasks:
    file: mmv/main.yml
  when: coreutils_enable_mmv
  tags:
    - mmv

- name: COREUTILS | Import mcfly tasks
  ansible.builtin.import_tasks:
    file: mcfly/main.yml
  when: coreutils_enable_mcfly
  tags:
    - mcfly
