#- name: COREUTILS | Include os independent variables
#  ansible.builtin.include_vars: main.yml
#  tags:
#    - always
#
#- name: COREUTILS | Import coreutils tasks
#  ansible.builtin.import_tasks: coreutils.yml
#  tags:
#    - coreutils

# GIT tasks and vars
- name: COREUTILS | Import git tasks
  ansible.builtin.import_tasks:
    file: git/main.yml
  when: coreutils_enable_git
  tags:
    - git

# BAT tasks and vars
- name: COREUTILS | Import bat tasks
  ansible.builtin.import_tasks:
    file: bat/main.yml
  when: coreutils_enable_bat
  tags:
    - bat
    - bat_extras

- name: COREUTILS | Import rye tasks
  ansible.builtin.import_tasks:
    file: rye/main.yml
  when: coreutils_enable_rye
  tags:
    - rye

- name: COREUTILS | Import aws_cli tasks
  ansible.builtin.import_tasks:
    file: aws_cli/main.yml
  when: coreutils_enable_aws_cli
  tags:
    - aws_cli

- name: COREUTILS | Import tealdeer tasks
  ansible.builtin.import_tasks:
    file: tealdeer/main.yml
  when: coreutils_enable_tealdeer
  tags:
    - tealdeer
