---
- name: COREUTILS | Import xdg_dirs role
  ansible.builtin.import_role:
    name: xdg_dirs

- name: COREUTILS | Import geerlingguy.homebrew rol
  ansible.builtin.import_role:
    name: geerlingguy.mac.homebrew
  when: ansible_system == "Darwin"

- name: COREUTILS | Import coreutils tasks
  ansible.builtin.import_tasks:
    file: coreutils/main.yml
  when: coreutils_enable_coreutils
  tags:
    - coreutils

- name: COREUTILS | Import tealdeer tasks
  ansible.builtin.import_tasks:
    file: tealdeer/main.yml
  when: coreutils_enable_tealdeer
  tags:
    - tealdeer

- name: COREUTILS | Import zoxide tasks
  ansible.builtin.import_tasks:
    file: zoxide/main.yml
  when: coreutils_enable_zoxide
  tags:
    - zoxide

- name: COREUTILS | Import sd tasks
  ansible.builtin.import_tasks:
    file: sd/main.yml
  when: coreutils_enable_sd
  tags:
    - sd

- name: COREUTILS | Import ripgrep tasks
  ansible.builtin.import_tasks:
    file: ripgrep/main.yml
  when: coreutils_enable_ripgrep
  tags:
    - ripgrep

- name: COREUTILS | Import yq tasks
  ansible.builtin.import_tasks:
    file: yq/main.yml
  when: coreutils_enable_yq
  tags:
    - yq
