- name: GIT | Install git on Linux
  ansible.builtin.package:
    name:
      - git
      - git-lfs
    state: present
  when: ansible_system == "Linux"
  become: true

- name: GIT | Install git on MacOS
  community.general.homebrew:
    name:
      - git
      - git-lfs
    state: present
  when: ansible_system == "Darwin"

- name: GIT | Create xdg configuration directories
  ansible.builtin.file:
    name: "{{ xdg_dirs_config }}/{{ item }}"
    state: directory
    mode: "0750"
  loop:
    - git
    - git/includes

- name: GIT | Link git config
  ansible.builtin.file:
    src: "{{ role_path }}/files/config"
    dest: "{{ xdg_dirs_config }}/git/config"
    state: link
    force: true

- name: GIT | Create git configuration
  ansible.builtin.template:
    src: generated.inc.j2
    dest: "{{ xdg_dirs_config }}/git/generated.inc"
    mode: "0640"
  when:
    - git_user_name != ""
    - git_user_mail != ""


- name: GIT | Create git includes
  ansible.builtin.template:
    src: includes.j2
    dest: "{{ xdg_dirs_config }}/git/includes/{{ item.path | hash('sha1') }}.inc"
    mode: "0640"
  loop: "{{ git_include_if }}"
