- name: GIT | Assert that coreutils_git_user_name is set
  ansible.builtin.assert:
    that:
      - "coreutils_git_user_name != ''"
    fail_msg: coreutils_git_user_name not set.
    success_msg: "Git user_name set to '{{ coreutils_git_user_name }}'"

- name: GIT | Assert that coreutils_git_user_mail is set
  ansible.builtin.assert:
    that:
      - "coreutils_git_user_mail != ''"
    fail_msg: coreutils_git_user_mail not set.
    success_msg: "Git user_mail set to '{{ coreutils_git_user_mail }}'"
