---
- name: WEZTERM | Include os vars
  ansible.builtin.include_vars:
    file: "{{ ansible_distribution | lower }}.yml"

- name: WEZTERM | Install packages on MacOS
  community.general.homebrew_cask:
    name: "{{ wezterm_packages }}"
    state: present
  when: ansible_system == "Darwin"

- name: WEZTERM | Install flathub package on Linux
  community.general.flatpak:
    name: "{{ wezterm_packages }}"
    state: present
  when:
    - ansible_system == "Linux"
    - ansible_distribution != "RedHat"

- name: WEZTERM | Install unsupported package of wezterm
  ansible.builtin.include_tasks:
    file: unsupported_wezterm.yml
  when: ansible_distribution == "RedHat"

- name: WEZTERM | Create wezterm config folder
  ansible.builtin.file:
    dest: "{{ xdg_dirs_config }}/{{ item }}"
    state: directory
    mode: "0750"
  loop:
    - wezterm
    - wezterm/colors

- name: WEZTERM | Link configuration files
  ansible.builtin.file:
    src: "{{ item }}"
    dest: "{{ xdg_dirs_config }}/wezterm/{{ item | basename }}"
    state: link
    force: true
  loop: "{{ query('ansible.builtin.fileglob', role_path + '/files/*.lua') }}"

- name: WEZTERM | Generate secrets.lua file
  ansible.builtin.template:
    src: secrets.lua.j2
    dest: "{{ xdg_dirs_config }}/wezterm/secrets.lua"
    mode: "0600"

- name: WEZTERM | Link tokyonight theme
  ansible.builtin.file:
    src: "{{ item }}"
    dest: "{{ xdg_dirs_config }}/wezterm/colors/{{ item | basename }}"
    state: link
    force: true
  loop: "{{ query('ansible.builtin.fileglob', xdg_dirs_config + '/themes/tokyonight.nvim/extras/wezterm/*.toml') }}"
