# BAT tasks and vars
- name: BAT | Include bat vars
  ansible.builtin.include_vars:
    file: main.yml
  tags:
    - bat
    - bat_extras

# BAT tasks and vars
- name: BAT | Include bat vars
  ansible.builtin.include_vars:
    file: "{{ ansible_distribution | lower }}.yml"
  tags:
    - bat
    - bat_extras

- name: BAT | Import bat task
  ansible.builtin.import_tasks:
    file: bat.yml
  tags:
    - bat

- name: BAT-EXTRAS | Import bat-extras tasks
  ansible.builtin.import_tasks:
    file: bat_extras.yml
  tags:
    - bat_extras

- name: BAT | Import config task
  ansible.builtin.import_tasks:
    file: config.yml
  tags:
    - bat_config
