---
- name: PODMAN | Get latest version for docker-credential-helpers
  ansible.builtin.uri:
    url: https://api.github.com/repos/docker/docker-credential-helpers/releases/latest
    headers: "{{ github_api_headers | to_json(vault_to_text=true) }}"
  register: podman_latest_release_json
  check_mode: false

- name: PODMAN | Get current installed version of docker-credential-helpers
  ansible.builtin.shell:
    cmd: "set -eo pipefail; {{ xdg_dirs_local_bin }}/docker-credential-pass version | cut -d 'v' -f 2"
  register: podman_current_version_cmd
  changed_when: false
  failed_when: false
  check_mode: false

- name: PODMAN | Register latest release version
  ansible.builtin.set_fact:
    podman_latest_version: "{{ podman_latest_release_json.json.tag_name.split('v')[1] }}"
    podman_current_version: "{{ podman_current_version_cmd.stdout | default('') }}"

- name: PODMAN | Latest docker-credential-helpers release version
  ansible.builtin.debug:
    var: podman_latest_version

- name: PODMAN | Current installed docker-credential-helpers version
  ansible.builtin.debug:
    var: podman_current_version

- name: PODMAN | Install or upgrade docker-credential-ecr-login
  when:
    - podman_current_version != podman_latest_version or podman_force_docker_credential_helper_install
  block:
    - name: PODMAN | Create tmp directory
      ansible.builtin.tempfile:
        prefix: podman_
        state: directory
      register: podman_tmp_dir
      changed_when: false
      check_mode: false

    - name: PODMAN | Set release full name
      ansible.builtin.set_fact:
        podman_full_release_name_pass: "docker-credential-pass-v{{ podman_latest_version }}.\
                                        {{ podman_os_arch[ansible_system][ansible_architecture] }}"
        podman_full_release_name_osxkeychain: "docker-credential-osxkeychain-v{{ podman_latest_version }}.\
                                               {{ podman_os_arch[ansible_system][ansible_architecture] }}"
        podman_full_release_name_secretservice: "docker-credential-secretservice-v{{ podman_latest_version }}.\
                                                {{ podman_os_arch[ansible_system][ansible_architecture] }}"
        podman_checksums: "checksums.txt"
      check_mode: false

    - name: PODMAN | Download checksum file
      ansible.builtin.uri:
        url: "https://github.com/docker/docker-credential-helpers/releases/download/v{{ podman_latest_version }}/{{ podman_checksums }}"
        return_content: true
      check_mode: false
      register: podman_checksums

    - name: PODMAN | Set checksum docker-credential-pass
      ansible.builtin.set_fact:
        podman_pass_checksum: "{{ podman_checksums.content | regex_findall('.*' + podman_full_release_name_pass + '.*') \
                               | first | split(' ') | first }}"
      check_mode: false

    - name: PODMAN | Set checksum for docker-credential-osxkeychain
      ansible.builtin.set_fact:
        podman_osxkeychain_checksum: "{{ podman_checksums.content | regex_findall('.*' + podman_full_release_name_osxkeychain + '.*') \
                                      | first | split(' ') | first }}"
      check_mode: false
      when: ansible_system == "Darwin"

    - name: PODMAN | Set checksum for docker-credential-secretservice
      ansible.builtin.set_fact:
        podman_secretservice_checksum: "{{ podman_checksums.content | regex_findall('.*' + podman_full_release_name_secretservice + '.*') \
                                        | first | split(' ') | first }}"
      check_mode: false
      when: ansible_system == "Linux"

    - name: PODMAN | Download latest docker-credential-pass release
      ansible.builtin.get_url:
        url: "https://github.com/docker/docker-credential-helpers/releases/download/v{{ podman_latest_version }}/{{ podman_full_release_name_pass }}"
        dest: "{{ xdg_dirs_local_bin }}/docker-credential-pass"
        checksum: "sha256:{{ podman_pass_checksum }}"
        mode: "0750"
      check_mode: false

    - name: PODMAN | Download latest docker-credential-osxkeychain release
      ansible.builtin.get_url:
        url: "https://github.com/docker/docker-credential-helpers/releases/download/v{{ podman_latest_version }}/{{ podman_full_release_name_osxkeychain }}"
        dest: "{{ xdg_dirs_local_bin }}/docker-credential-osxkeychain"
        checksum: "sha256:{{ podman_osxkeychain_checksum }}"
        mode: "0750"
      check_mode: false
      when: ansible_system == "Darwin"

    - name: PODMAN | Download latest docker-credential-secretservice release
      ansible.builtin.get_url:
        url: "https://github.com/docker/docker-credential-helpers/releases/download/v{{ podman_latest_version }}/{{ podman_full_release_name_secretservice }}"
        dest: "{{ xdg_dirs_local_bin }}/docker-credential-secretservice"
        checksum: "sha256:{{ podman_secretservice_checksum }}"
        mode: "0750"
      check_mode: false
      when: ansible_system == "Linux"
