---
- name: PODMAN | Get latest version for docker-credential-ecr-login
  ansible.builtin.uri:
    url: https://api.github.com/repos/awslabs/amazon-ecr-credential-helper/releases/latest
    headers: "{{ github_api_headers | to_json(vault_to_text=true) }}"
  register: podman_latest_release_json
  check_mode: false

- name: PODMAN | Get current installed version of docker-credential-ecr-login
  ansible.builtin.shell:
    cmd: "set -eo pipefail; {{ xdg_dirs_local_bin }}/docker-credential-ecr-login -v | head -n 2 | tail -n 1 | cut -d ':' -f 2 | tr -d ' '"
  register: podman_current_version_cmd
  changed_when: false
  failed_when: false
  check_mode: false

- name: PODMAN | Register latest release version
  ansible.builtin.set_fact:
    podman_latest_version: "{{ podman_latest_release_json.json.tag_name.split('v')[1] }}"
    podman_current_version: "{{ podman_current_version_cmd.stdout | default('') }}"

- name: PODMAN | Latest docker-credential-ecr-login release version
  ansible.builtin.debug:
    var: podman_latest_version

- name: PODMAN | Current installed docker-credential-ecr-login version
  ansible.builtin.debug:
    var: podman_current_version

- name: PODMAN | Install or upgrade docker-credential-ecr-login
  when:
    - podman_current_version != podman_latest_version or podman_force_docker_ecr_credential_helper_install
  block:
    - name: PODMAN | Create tmp directory
      ansible.builtin.tempfile:
        prefix: podman_
        state: directory
      register: podman_tmp_dir
      changed_when: false
      check_mode: false

    - name: PODMAN | Set release full name
      ansible.builtin.set_fact:
        podman_full_release_name: "{{ podman_os_arch[ansible_system][ansible_architecture] }}"
      check_mode: false

    - name: PODMAN | Download checksum file
      ansible.builtin.uri:
        url: "https://amazon-ecr-credential-helper-releases.s3.us-east-2.amazonaws.com/\
              {{ podman_latest_version }}/{{ podman_full_release_name }}/docker-credential-ecr-login.sha256"
        return_content: true
      check_mode: false
      register: podman_checksums

    - name: PODMAN | Set checksum for system and architecture archive
      ansible.builtin.set_fact:
        podman_file_checksum: "{{ podman_checksums.content | split(' ') | first }}"
      check_mode: false

    - name: PODMAN | Download latest release
      ansible.builtin.get_url:
        url: "https://amazon-ecr-credential-helper-releases.s3.us-east-2.amazonaws.com/\
              {{ podman_latest_version }}/{{ podman_full_release_name }}/docker-credential-ecr-login"
        dest: "{{ podman_tmp_dir.path }}"
        checksum: "sha256:{{ podman_file_checksum }}"
        mode: "0640"
      check_mode: false
      register: podman_downloaded_release

    - name: PODMAN | Copy binary
      ansible.builtin.copy:
        src: "{{ podman_tmp_dir.path }}/docker-credential-ecr-login"
        dest: "{{ xdg_dirs_local_bin }}/docker-credential-ecr-login"
        mode: "0750"
      diff: false
