---
- name: PODMAN | Include podman vars
  ansible.builtin.include_vars:
    file: main.yml

- name: PODMAN | Include os dependent vars
  ansible.builtin.include_vars:
    file: "{{ ansible_distribution | lower }}.yml"

- name: PODMAN | Install podman on linux
  ansible.builtin.package:
    name: "{{ podman_packages }}"
    state: present
  when: ansible_system == "Linux"
  become: true

- name: PODMAN | Install podman on Darwin
  community.general.homebrew:
    name: "{{ podman_packages }}"
    state: present
  when: ansible_system == "Darwin"

- name: PODMAN | Create configuration directory
  ansible.builtin.file:
    path: "{{ xdg_dirs_config }}/containers"
    state: directory
    mode: "0755"

- name: PODMAN | Install podman-desktop
  when: podman_enable_podman_desktop
  block:
    - name: PODMAN | Install podman-desktop on linux
      community.general.flatpak:
        name: "{{ podman_desktop_packages }}"
        state: present
      when: ansible_system == "Linux"

    - name: PODMAN | Install podman-desktop on Darwin
      community.general.homebrew:
        name: "{{ podman_desktop_packages }}"
        state: present
      when: ansible_system == "Darwin"

- name: PODMAN | Install credentials helpers
  ansible.builtin.include_tasks:
    file: "{{ item }}"
  loop:
    - docker_credential_helper.yml
    - ecr_credential_helper.yml
