---
- name: PODMAN | Install podman on linux
  community.general.flatpak:
    name: io.podman_desktop.PodmanDesktop
    state: present
  when: ansible_system == "Linux"

- name: PODMAN | Install podman on Darwin
  community.general.homebrew:
    name: podman-desktop
    state: present
  when: ansible_system == "Darwin"
