export EZA_CONFIG_DIR="$XDG_CONFIG_HOME/eza"
alias eza="eza --icons --group-directories-first --group --header --mounts --git"
alias la="eza -a"
alias ll="eza -l"
alias lla="eza -la"
alias ls="eza"
alias lt="eza --tree"
alias tree="eza --tree"
