---
# Only provision default settings once this role will
# put a file under ~/.local/state/macos_settings_state
# to ensure that this role only runs once and for all
# subsequent runs, the user must either delete the file
# or set this variable to true
macos_force_default_settings: false

macos_settings_state_file: macos_settings_state

# Default settings for documentation see
# https://daiderd.com/nix-darwin/manual/index.html#opt-system.defaults._.GlobalPreferences_._com.apple.mouse.scaling_
macos_default_settings:
  NSGlobalDomain:
    AppleICUForce24HourTime: true
    AppleInterfaceStyle: Light
    AppleShowAllExtensions: true
    AppleShowAllFiles: true
    AppleShowScrollBars: "Automatic"
    AppleWindowTabbingMode: "always"
    InitialKeyRepeat: 15
    KeyRepeat: 2
    NSDisableAutomaticTermination: true
    NSDocumentSaveNewDocumentsToCloud: false
    NSNavPanelExpandedStateForSaveMode: true
    NSNavPanelExpandedStateForSaveMode2: true
    NSTableViewDefaultSizeMode: 1
    NSWindowResizeTime: 0.001
    PMPrintingExpandedStateForPrint: true
    PMPrintingExpandedStateForPrint2: true
    "com.apple.keyboard.fnState": false
    "com.apple.swipescrolldirection": false
    "com.apple.trackpad.scaling": 1.5

  com.apple.dock:
    appswitcher-all-displays: true
    autohide: true
    autohide-delay: 0.25
    expose-group-by-app: true
    launchanim: true
    magnification: false
    mineffect: "scale"
    minimize-to-application: true
    orientation: "bottom"
    show-process-indicators: true
    show-recents: false
    tilesize: 39
    wvous-bl-corner: 1
    wvous-br-corner: 1
    wvous-tl-corner: 1
    wvous-tr-corner: 1

  com.apple.finder:
    AppleShowAllExtensions: true
    AppleShowAllFiles: true
    FXEnableExtensionChangeWarning: false
    FXPreferredViewStyle: "Nlsv"
    QuitMenuItem: true
    ShowPathbar: true
    ShowStatusBar: true
    _FXShowPosixPathInTitle: true
    _FXSortFoldersFirst: true
    FXDefaultSearchScope: "SCcf"

  com.apple.menuextra.clock:
    Show24Hour: true
    ShowAMPM: false
    ShowDate: 0
    ShowDayOfMonth: true
    ShowDayOfWeek: true
    ShowSeconds: true

  com.apple.screensaver:
    askForPassword: true
    askForPasswordDelay: 0

  com.apple.spaces:
    spans-displays: true

  com.apple.AppleMultitouchTrackpad:
    ActuationStrength: 1
    Clicking: true
    Dragging: true
    FirstClickThreshold: 0
    SecondClickThreshold: 0
    TrackpadRightClick: true
    TrackpadThreeFingerDrag: false

  com.apple.desktopservices:
    # Avoid creating .DS_Store files on network or USB volumes
    DSDontWriteNetworkStores: true
    DSDontWriteUSBStores: true

  com.apple.AdLib:
    allowApplePersonalizedAdvertising: false

  # Prevent Photos from opening automatically when devices are plugged in
  com.apple.ImageCapture:
    disableHotPlug: true
