galaxy_info:
  author: Daniel von Essen
  description: Install and configure podman
  issue_tracker_url: https://gitlab.com/bitfooxyz/dots/-/issues
  license: MIT
  min_ansible_version: "2.9"
  platforms:
    - name: MacOSX
      versions:
        - all
    - name: Fedora
      versions:
        - "40"
  galaxy_tags:
    - container
    - podman
    - docker
