# BAT tasks and vars
- name: BAT | Include bat vars
  ansible.builtin.include_vars:
    file: bat/main.yml
  tags:
    - bat
    - bat_extras

# BAT tasks and vars
- name: BAT | Include bat vars
  ansible.builtin.include_vars:
    file: "bat/{{ ansible_distribution | lower }}.yml"
  tags:
    - bat
    - bat_extras

- name: BAT | Import bat task
  ansible.builtin.import_tasks:
    file: bat/bat.yml
  tags:
    - bat

- name: BAT-EXTRAS | Import bat-extras tasks
  ansible.builtin.import_tasks:
    file: bat/bat_extras.yml
  tags:
    - bat_extras
